codecov:
  require_ci_to_pass: true

coverage:
  status:
    project: off
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# excluding generated files and examples from the coverage report
ignore:
  - "**/example/"
  - "examples"
  - "**/*.g.dart"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false