name: polkadart
repository: https://github.com/leonardocustodio/polkadart

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**

scripts:
  test:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart test --coverage="coverage"'
  
  format:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart format .'
  
  analyze:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart analyze --fatal-infos .'