name: polkadart
repository: https://github.com/leonardocustodio/polkadart

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**

scripts:
  test:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart test --coverage="coverage"'

  coverage:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart run coverage:format_coverage --lcov --in=coverage --out=coverage/coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib'
  
  format:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart format .'
  
  analyze:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart analyze --fatal-infos .'