name: polkadart
repository: https://github.com/rankanizer/polkadart

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**

scripts:
  test:
    run: fvm dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'fvm dart test --coverage="coverage"'
  
  format:
    run: fvm dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'fvm dart format --set-exit-if-changed .'
  
  analyze:
    run: fvm dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'fvm dart analyze .'
  
  # CI commands
  # OBS: CI we do not use FVM
  test:ci:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart test --coverage="coverage"'
  
  format:ci:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart format --set-exit-if-changed .'
  
  analyze:ci:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart analyze .'