name: polkadart
repository: https://github.com/rankanizer/polkadart

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        dart analyze .
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  test:
    run: git lfs fetch && git lfs checkout && melos run test:dart --no-select
    description: Run all Dart tests in this project.

  test:dart:
    run: melos exec  -c 1 --fail-fast -- "\$MELOS_ROOT_PATH/scripts/coverage.sh"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test