name: scale_codec_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  blake2b: ^0.2.2
  code_builder: ^4.4.0
  dart_style: ^2.2.4
  http: ^0.13.5
  hex: ^0.2.0
  recase: ^4.1.0
  polkadart_scale_codec:
    path: ../polkadart_scale_codec

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
