name: scale_codec_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  code_builder: ^4.4.0 # BSD-3-Clause
  dart_style: ^2.2.4 # BSD-3-Clause
  recase: ^4.1.0 # BSD-2-Clause
  frame_primitives:
    path: ../frame_primitives
  polkadart_scale_codec:
    path: ../polkadart_scale_codec

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
