include: package:lints/recommended.yaml

linter:
  rules:
    constant_identifier_names: false
    overridden_fields: false
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    non_constant_identifier_names: false

analyzer:
  errors:
    use_string_in_part_of_directives: ignore
    unnecessary_library_name: ignore