name: polkadart
description: polkadart
version: 0.0.1
homepage: https://pub.dev

# TODO: Remove this when polkadart_scale_codec is published
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  substrate_metadata: 
    path: ../packages/substrate_metadata

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true