name: polkadart
description: polkadart
version: 0.0.1
homepage: https://pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true