name: Build Docker Image

on:
  pull_request:
    paths:
      - "!docs/**"
      - "!.github/workflows/**"
      - "packages/**"
      - ".github/workflows/docker_build.yml"
      - "Dockerfile"
  push:
    branches:
      - main
       
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build docker image
        run: |
          docker build -t leonardocustodio/polkadart .
