name: Build Docs
on:
  push:


jobs:
  build:
    name: Check docs builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        sparse-checkout: docs

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
