name: Publish substrate_bip39
on:
  push:
    tags:
      - 'substrate_bip39-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
      working-directory: packages/substrate_bip39