name: Publish to Pub.dev

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - ink_abi
          - polkadart
          - polkadart_cli
          - polkadart_keyring
          - polkadart_scale_codec
          - secp256k1_ecdsa
          - ss58
          - sr25519
          - substrate_metadata
          - substrate_bip39

    steps:
      - uses: actions/checkout@v4

      - name: Publish if new
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          relativePath: ./packages/${{ matrix.package }}
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          suppressBuildRunner: true
          skipTests: true

      - name: Tag commit
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
